### ISSUE TITLE
Dummy content for several countries

### ISSUE THREAD

**Issue by yatil** [w3c/wai-policies-prototype#188] opened 2017-05-10 18:29 UTC
I guess @maryjom is aware of it, but I just wanted to make a record:

* [ ] Italy: https://github.com/w3c/wai-policies-prototype/blob/gh-pages/_policies/italy.md
* [ ] Portugal: https://github.com/w3c/wai-policies-prototype/blob/gh-pages/_policies/portugal.md
* [ ] Spain: https://github.com/w3c/wai-policies-prototype/blob/gh-pages/_policies/spain.md
* [ ] Switzerland: https://github.com/w3c/wai-policies-prototype/blob/gh-pages/_policies/switzerland.md

**Comment by maryjom** [comment] 2017-05-10 19:35
This is a duplicate of #133. I am aware of the remaining countries missing info and have people on it.  Spoke with Robert about this on Monday and we agreed that if I fail to get the info prior to AccessU I'll simply delete the dummy country entries.

**Closed by maryjom** 2017-05-10 19:35 UTC
Labels: content
